# Set update schedule for GitHub Actions and Maven dependencies
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "daily"
    assignees:
      - "aguirre-jes"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      # Check for updates to Maven dependencies every day
      interval: "daily"
    assignees:
      - "aguirre-jes"
  - package-ecosystem: "docker"
    directory: "/src/main/docker"
    schedule:
      # Check for updates to Maven dependencies every day
      interval: "daily"
    assignees:
      - "aguirre-jes"